[dataset]
name="BigVul"
description = "A C/C++ Code Vulnerability Dataset with Code Changes and CVE Summaries"

version = "1.0.0"
license = "MIT"
languages="cpp"
has_runable_code_or_test_cases=false

[dataset.files]
data="datasets/bigvul/extracted_data.csv"


[dataset.fields]
function="function"
label="label"
vuln_label_value=1
cve="cve"
cwe="cwe"
project="project"

[dataset.analysis.quiality_metrics]
completeness=true
diversity=true
balance=true
timespan=true
uniqueness=true
cross_contamination=true

[dataset.analysis.structural_metrics]
loc=true
tokens=true
cyclomatic_complexity=true